"""
Tune DSL — C++ code generator.

Takes a SemanticResult and emits a self-contained .cpp file that:
  - holds the note events as a static const array (beats already converted
    to seconds here in Python -- the C++ side does zero music-theory logic,
    only numeric sample synthesis)
  - fills a sample buffer with a tight, vectorizable per-event loop
  - normalizes and writes a 16-bit PCM WAV file

The math here is intentionally identical to reference.py so the two
outputs can be numerically diffed (see tests/test_codegen_diff.py).
"""

import math

from semantic import SemanticResult

WAVEFORM_ID = {"sine": 0, "square": 1, "saw": 2, "triangle": 3, "pulse": 4, "noise": 5}
EFFECT_ID = {"lowpass": 0, "delay": 1, "highpass": 2, "distortion": 3, "tremolo": 4}


class CppBackendError(Exception):
    pass


def _beats_to_seconds(beats: float, tempo_bpm: float) -> float:
    return beats * (60.0 / tempo_bpm)


def generate_cpp(result: SemanticResult, sample_rate: int = 44100) -> str:
    all_events = []
    for _instrument, pattern in result.plays:
        all_events.extend(result.note_events[pattern])

    # `slide` (frequency glide) and per-instrument `envelope` overrides
    # are implemented in reference.py (the Python backend) but not yet
    # ported here -- rather than silently ignore them and produce audio
    # that doesn't match what the Python backend would render for the
    # same source, fail clearly and say so.
    for ev in all_events:
        if getattr(ev, "slide_from_freq", None) is not None:
            raise CppBackendError(
                "the C++ backend does not yet support `slide` (frequency glide) -- "
                "use --backend python for programs that use slide"
            )
        if getattr(ev, "attack_sec", None) is not None or getattr(ev, "release_sec", None) is not None:
            raise CppBackendError(
                "the C++ backend does not yet support per-instrument `envelope` "
                "overrides -- use --backend python for programs that use envelope"
            )

    # Convert beats -> seconds -> integer sample counts HERE in Python,
    # using the exact same rounding as reference.py (Python's round(), i.e.
    # round-half-to-even). This is deliberate: C++'s llround() rounds
    # half-away-from-zero, a different tie-breaking rule. Musical durations
    # land on exact .5-sample boundaries often enough that if each side
    # independently rounded start_sec*sample_rate, they'd disagree on some
    # notes' start sample by 1 -- shifting that note's whole waveform phase
    # for its entire duration. Embedding pre-rounded integers instead
    # removes the disagreement: C++ has no rounding decision left to make.
    lines = []
    for ev in all_events:
        freq = ev.freq_hz if ev.freq_hz is not None else -1.0
        start_sec = _beats_to_seconds(ev.start_beat, result.tempo_bpm)
        dur_sec = _beats_to_seconds(ev.duration_beats, result.tempo_bpm)
        start_sample = int(round(start_sec * sample_rate))
        n_samples = int(round(dur_sec * sample_rate))
        wid = WAVEFORM_ID[ev.waveform]
        vel = getattr(ev, "velocity", 1.0)
        lines.append(f"    {{ {freq!r}f, {start_sample}, {n_samples}, {wid}, {vel!r} }},")
    events_array = "\n".join(lines) if lines else "    // (no events)"
    num_events = len(all_events)

    effect_lines = []
    for name, args in (result.effects or []):
        eid = EFFECT_ID[name]
        a0 = args[0] if len(args) > 0 else 0.0
        a1 = args[1] if len(args) > 1 else 0.0
        effect_lines.append(f"    {{ {eid}, {a0!r}, {a1!r} }},")
    effects_array = "\n".join(effect_lines) if effect_lines else "    // (no effects)"
    num_effects = len(result.effects or [])

    # Buffer length must be computed the exact same way reference.py does it
    # (from total_beats -> seconds -> ceil), NOT derived from
    # max(start_sample + n_samples) over the individual per-event rounded
    # values -- those two routes can legitimately disagree by a sample.
    if all_events:
        total_beats = max(ev.start_beat + ev.duration_beats for ev in all_events)
        total_sec = _beats_to_seconds(total_beats, result.tempo_bpm)
        total_samples_const = int(math.ceil(total_sec * sample_rate)) + 1
    else:
        total_samples_const = 1

    return f"""// Auto-generated by Tune DSL codegen.py -- do not edit by hand.
//
// Recommended build: g++ -O3 -march=native -ffast-math -flto -funroll-loops -o song song.cpp
//
// NOTE on -ffast-math: it's required for the per-sample synthesis loop
// below to auto-vectorize (without it, GCC treats fmod/sin's errno side
// effects as blocking; see codegen.py's comments for the full story of
// how this loop was made vectorizable). The tradeoff: -ffast-math allows
// floating-point reassociation, which can very rarely flip a comparison
// at an exact tie (e.g. a phase value that lands mathematically exactly
// on 0.5) -- a single sample might differ from a strict-IEEE reference
// implementation. In practice this is a ~22-microsecond, inaudible
// event, not a systematic error. If bit-for-bit determinism against the
// Python reference matters more than raw throughput, compile with
// `-fno-math-errno` alone instead of `-ffast-math` -- this preserves
// strict comparisons (no reassociation) at the cost of the hot loop no
// longer auto-vectorizing.
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cmath>
#include <vector>
#include <algorithm>

struct NoteEvent {{
    float freq_hz;          // -1.0f means "rest" (silence)
    long start_sample;       // pre-rounded in Python -- see codegen.py comment
    long n_samples;
    int waveform_id;          // 0=sine 1=square 2=saw 3=triangle 4=pulse 5=noise
    double velocity;           // 0..1 volume multiplier
}};

struct Effect {{
    int type;   // 0=lowpass(arg0=cutoff_hz)  1=delay(arg0=delay_sec, arg1=feedback)
                // 2=highpass(arg0=cutoff_hz)  3=distortion(arg0=drive)
                // 4=tremolo(arg0=rate_hz, arg1=depth)
    double arg0;
    double arg1;
}};

static const int SAMPLE_RATE = {sample_rate};
static const int NUM_EVENTS = {num_events};
static const long TOTAL_SAMPLES = {total_samples_const};
static const NoteEvent events[NUM_EVENTS > 0 ? NUM_EVENTS : 1] = {{
{events_array}
}};

static const int NUM_EFFECTS = {num_effects};
static const Effect effects_list[NUM_EFFECTS > 0 ? NUM_EFFECTS : 1] = {{
{effects_array}
}};

// Deterministic avalanche hash (triple32) used by the "noise" waveform.
// MUST match reference.py's _hash_u32 exactly (same constants, same
// operation order) -- unsigned overflow wraps by the C++ standard, same
// as numpy's uint32 arithmetic, so the two stay bit-identical.
inline uint32_t hash_u32(uint32_t x) {{
    x ^= x >> 16;
    x *= 0x7feb352du;
    x ^= x >> 15;
    x *= 0x846ca68bu;
    x ^= x >> 16;
    return x;
}}

// One sample of the given waveform. `phase` is fractional cycle position in
// [0,1) (used by all waveforms except noise); `idx` is the absolute sample
// index (used only by noise, which ignores phase/frequency entirely).
// Templated on waveform id so the switch is resolved at COMPILE time per
// specialization, not per-sample at runtime -- this is what lets the
// sample loop below vectorize (a runtime switch inside the loop counts as
// "control flow" and blocks auto-vectorization).
template <int WAVEFORM_ID>
inline double waveform_sample(double phase, uint32_t idx);

template <> inline double waveform_sample<0>(double phase, uint32_t) {{ return std::sin(2.0 * M_PI * phase); }}
template <> inline double waveform_sample<1>(double phase, uint32_t) {{ return 1.0 - 2.0 * std::floor(2.0 * phase); }}
template <> inline double waveform_sample<2>(double phase, uint32_t) {{ return 2.0 * phase - 1.0; }}
template <> inline double waveform_sample<3>(double phase, uint32_t) {{ return 2.0 * std::fabs(2.0 * phase - 1.0) - 1.0; }}
template <> inline double waveform_sample<4>(double phase, uint32_t) {{ return 1.0 - 2.0 * std::min(1.0, std::floor(4.0 * phase)); }}
template <> inline double waveform_sample<5>(double, uint32_t idx) {{
    uint32_t h = hash_u32(idx);
    return ((double)h / 4294967295.0) * 2.0 - 1.0;
}}

// Synthesizes one event's samples into `buffer`, branch-free per sample:
// the envelope multiplier is computed with min()/max() instead of if/else,
// and the waveform is fixed by the template parameter, not a runtime switch.
// This is the actual vectorization target -- verify with:
//   g++ -O3 -march=native -ffast-math -fopt-info-vec-optimized
template <int WAVEFORM_ID>
__attribute__((noinline))
void synth_event(std::vector<double>& buffer, long total_samples,
                         float freq_hz, long start_sample, long n, double velocity) {{
    long fade_samples = std::min((long)(0.005 * SAMPLE_RATE), n / 2);
    double inv_fade = fade_samples > 1 ? 1.0 / (double)(fade_samples - 1) : 0.0;

    long lo = std::max(0L, -start_sample);
    long hi = std::min(n, total_samples - start_sample);

    // Raw restrict-qualified pointer: std::vector::operator[] doesn't carry
    // alias information to the compiler, but a plain __restrict pointer
    // does -- this tells GCC no other pointer in this function can alias
    // buf, which can matter for the vectorizer's cost/legality analysis.
    double* __restrict buf = buffer.data();

    for (long s = lo; s < hi; ++s) {{
        double t = (double)s / SAMPLE_RATE;
        double raw = (double)freq_hz * t;
        double phase = raw - std::floor(raw);  // manual wrap: std::fmod blocks
                                                // auto-vectorization (verified
                                                // empirically -- see codegen.py)
        uint32_t idx = (uint32_t)(start_sample + s);
        double wave = waveform_sample<WAVEFORM_ID>(phase, idx);

        // branchless envelope: 1.0 in the steady region, ramps at the
        // edges, via two clamped linear terms combined with min()
        double attack = fade_samples > 1 ? (double)s * inv_fade : 1.0;
        double release = fade_samples > 1 ? (double)(n - 1 - s) * inv_fade : 1.0;
        double env = std::min(1.0, std::min(attack, release));
        env = std::max(0.0, env);

        buf[start_sample + s] += wave * env * velocity;
    }}
}}

// One-pole IIR low-pass, in place. Inherently sequential (each output
// depends on the previous), so this is a plain loop -- matches
// reference.py's apply_lowpass exactly (same recurrence, same order).
void apply_lowpass(std::vector<double>& buffer, double cutoff_hz) {{
    if (cutoff_hz <= 0.0 || buffer.empty()) return;
    double dt = 1.0 / SAMPLE_RATE;
    double rc = 1.0 / (2.0 * M_PI * cutoff_hz);
    double alpha = dt / (rc + dt);
    double prev = 0.0;
    for (size_t i = 0; i < buffer.size(); ++i) {{
        prev = prev + alpha * (buffer[i] - prev);
        buffer[i] = prev;
    }}
}}

// Feedback delay line: y[n] = x[n] + feedback*y[n-delay_samples]. Extends
// the buffer so the delay tail can ring out. Matches reference.py's
// apply_delay exactly (same tail length, same recurrence).
std::vector<double> apply_delay(const std::vector<double>& buffer, double delay_sec, double feedback) {{
    long delay_samples = (long)std::llround(delay_sec * SAMPLE_RATE);
    if (delay_samples <= 0 || buffer.empty()) return buffer;
    long tail = delay_samples * 4;
    std::vector<double> out(buffer.size() + tail, 0.0);
    for (size_t i = 0; i < out.size(); ++i) {{
        double x = (i < buffer.size()) ? buffer[i] : 0.0;
        double fb = ((long)i >= delay_samples) ? out[i - delay_samples] * feedback : 0.0;
        out[i] = x + fb;
    }}
    return out;
}}

// One-pole high-pass, in place: y[n] = alpha*(y[n-1] + x[n] - x[n-1]).
// Sequential like lowpass -- matches reference.py's apply_highpass exactly.
void apply_highpass(std::vector<double>& buffer, double cutoff_hz) {{
    if (cutoff_hz <= 0.0 || buffer.empty()) return;
    double dt = 1.0 / SAMPLE_RATE;
    double rc = 1.0 / (2.0 * M_PI * cutoff_hz);
    double alpha = rc / (rc + dt);
    double prev_y = 0.0;
    double prev_x = buffer[0];
    for (size_t i = 0; i < buffer.size(); ++i) {{
        double x = buffer[i];
        prev_y = alpha * (prev_y + x - prev_x);
        buffer[i] = prev_y;
        prev_x = x;
    }}
}}

// Soft-clip saturation via tanh, peak-preserving (input +/-1 -> output
// +/-1). Purely elementwise -- matches reference.py's apply_distortion.
void apply_distortion(std::vector<double>& buffer, double drive) {{
    if (drive <= 0.0 || buffer.empty()) return;
    double norm = std::tanh(drive);
    if (norm < 1e-9) return;
    for (double& v : buffer) v = std::tanh(drive * v) / norm;
}}

// Amplitude modulation by a slow sine LFO. Purely elementwise, like
// distortion -- matches reference.py's apply_tremolo exactly.
void apply_tremolo(std::vector<double>& buffer, double rate_hz, double depth) {{
    if (rate_hz <= 0.0 || depth <= 0.0 || buffer.empty()) return;
    depth = std::min(depth, 1.0);
    for (size_t i = 0; i < buffer.size(); ++i) {{
        double t = (double)i / SAMPLE_RATE;
        double lfo = 0.5 + 0.5 * std::sin(2.0 * M_PI * rate_hz * t);
        buffer[i] = buffer[i] * (1.0 - depth * lfo);
    }}
}}

int main(int argc, char** argv) {{
    const char* out_path = argc > 1 ? argv[1] : "output.wav";

    long total_samples = TOTAL_SAMPLES;
    std::vector<double> buffer(total_samples, 0.0);

    for (int i = 0; i < NUM_EVENTS; ++i) {{
        const NoteEvent& ev = events[i];
        if (ev.freq_hz < 0.0f) continue;  // rest: contributes silence
        if (ev.n_samples <= 0) continue;

        switch (ev.waveform_id) {{
            case 0: synth_event<0>(buffer, total_samples, ev.freq_hz, ev.start_sample, ev.n_samples, ev.velocity); break;
            case 1: synth_event<1>(buffer, total_samples, ev.freq_hz, ev.start_sample, ev.n_samples, ev.velocity); break;
            case 2: synth_event<2>(buffer, total_samples, ev.freq_hz, ev.start_sample, ev.n_samples, ev.velocity); break;
            case 3: synth_event<3>(buffer, total_samples, ev.freq_hz, ev.start_sample, ev.n_samples, ev.velocity); break;
            case 4: synth_event<4>(buffer, total_samples, ev.freq_hz, ev.start_sample, ev.n_samples, ev.velocity); break;
            case 5: synth_event<5>(buffer, total_samples, ev.freq_hz, ev.start_sample, ev.n_samples, ev.velocity); break;
        }}
    }}

    // apply effects in the order they were declared, before normalization
    // (matches reference.py's render()/apply_effects())
    for (int i = 0; i < NUM_EFFECTS; ++i) {{
        const Effect& fx = effects_list[i];
        if (fx.type == 0) {{
            apply_lowpass(buffer, fx.arg0);
        }} else if (fx.type == 1) {{
            buffer = apply_delay(buffer, fx.arg0, fx.arg1);
        }} else if (fx.type == 2) {{
            apply_highpass(buffer, fx.arg0);
        }} else if (fx.type == 3) {{
            apply_distortion(buffer, fx.arg0);
        }} else if (fx.type == 4) {{
            apply_tremolo(buffer, fx.arg0, fx.arg1);
        }}
    }}

    // normalize (leave headroom, matches reference.py's 0.95 peak target)
    double peak = 0.0;
    for (double v : buffer) peak = std::max(peak, std::fabs(v));
    if (peak > 1e-9) {{
        double scale = 0.95 / peak;
        for (double& v : buffer) v *= scale;
    }}

    // convert to 16-bit PCM
    std::vector<int16_t> pcm(buffer.size());
    for (size_t i = 0; i < buffer.size(); ++i) {{
        double v = std::max(-1.0, std::min(1.0, buffer[i]));
        pcm[i] = (int16_t)std::lround(v * 32767.0);
    }}

    // write WAV (mono, 16-bit PCM) -- header layout matches reference.py's write_wav
    FILE* f = fopen(out_path, "wb");
    if (!f) {{ std::fprintf(stderr, "failed to open %s for writing\\n", out_path); return 1; }}

    uint32_t data_bytes = (uint32_t)(pcm.size() * sizeof(int16_t));
    uint16_t num_channels = 1, bits_per_sample = 16;
    uint32_t byte_rate = SAMPLE_RATE * num_channels * bits_per_sample / 8;
    uint16_t block_align = num_channels * bits_per_sample / 8;
    uint32_t riff_size = 36 + data_bytes;
    uint32_t fmt_size = 16;
    uint16_t audio_format = 1;
    uint32_t sample_rate_u32 = SAMPLE_RATE;

    fwrite("RIFF", 1, 4, f);
    fwrite(&riff_size, 4, 1, f);
    fwrite("WAVE", 1, 4, f);
    fwrite("fmt ", 1, 4, f);
    fwrite(&fmt_size, 4, 1, f);
    fwrite(&audio_format, 2, 1, f);
    fwrite(&num_channels, 2, 1, f);
    fwrite(&sample_rate_u32, 4, 1, f);
    fwrite(&byte_rate, 4, 1, f);
    fwrite(&block_align, 2, 1, f);
    fwrite(&bits_per_sample, 2, 1, f);
    fwrite("data", 1, 4, f);
    fwrite(&data_bytes, 4, 1, f);
    fwrite(pcm.data(), sizeof(int16_t), pcm.size(), f);
    fclose(f);

    std::printf("wrote %s (%zu samples, %.2f sec)\\n", out_path, pcm.size(), (double)pcm.size() / SAMPLE_RATE);
    return 0;
}}
"""